version: '3.1'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strong
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - postgres-network


volumes:
  postgres:

networks:
  postgres-network:
    driver: bridge